### ISSUE TITLE
Schema 2.1 revision: resolve validated descriptor-semantic gaps

### ISSUE THREAD

**Issue by evomimic** [memetic-activation-platform/map-dev-docs#9]
# Schema 2.1 revision: resolve validated descriptor-semantic gaps

## 1. Summary (Required)

**What is the enhancement?**  
Define and ratify a bounded Schema 2.1 revision that resolves the validated semantic gaps in the Schema 2.0 descriptor kernel before those semantics are treated as frozen or implemented as durable runtime behavior.

The revision covers endpoint classification, key-rule applicability, schema ownership of configured schema entities, abstract-descriptor minimum policy, executable value definitions, and inverse-occurrence binding. It also records Core anchor assertions and reconciles closely coupled wording and diagram drift.

---

## 2. Problem Statement (Required)

**Why is this needed?**  
The Schema 2.0 critical review identified several cases where the current normative rules admit a graph that is category-compatible but not semantically executable, or where a required semantic operation cannot be computed unambiguously.

The assessed issues are:

1.  The current descriptor-driven definition of inheritance has an unresolved bootstrap cycle. `InheritanceMode(M)` is defined as the required singular value in `EffectiveMemberDefinition(M)`. Computing `EffectiveMemberDefinition(M)` requires `ConformanceContract(M)`, which requires `EffectiveInstanceContract(D(M))`. That contract requires effective `InstanceProperties` and `InstanceRelationships`, whose resolution again requires the member descriptors’ `InheritanceMode`.
2. `DS-OCC-002` combines `L(D(H))` and `L(H)` in one predicate. This cannot express “the endpoint holon is itself a descriptor of category X”; a requirement for `TypeDescriptor` also matches an ordinary holon whose describing type descends from `TypeDescriptor`.
3. `DS-KEY-002` says a selected key rule is executable, but does not define an applicability/totality predicate that proves its inputs are contract-bound, creation-time available, representable, and canonically ordered. Configured `FormatRule` instances and abstract relationship descriptors make this observable.
4. `ComponentOf` gives descriptors an owner schema, while generic configured key-rule and value-constraint holons intentionally receive no implicit `ComponentOf`. Their source/target schema, dependency validation, and key scope are consequently undefined.
5. `DS-CONFORM-002` describes member-specific abstract completeness but currently derives it from membership in `EffectiveInstanceContract(MetaTypeDescriptor.HolonType)`. Contract refactoring can therefore change minimum policy implicitly.
6. A concrete property descriptor must select a ValueType-family target, but no predicate requires that selected value definition to be executable for embedded runtime values.
7. Declared/inverse semantic occurrence pairing is specified, but the binding and conformance route for a materialized inverse occurrence at its target needs an explicit rule.
The Core corpus and runtime migration already depend on these boundaries. Encoding a local implementation choice now would create incompatible semantics for TDL, JSON loading, Holon Validation, queries, and future extension schemas.

---

## 3. Dependencies (Required)

**Does this depend on other issues or features?**  

- Depends on resolution of the separately active Schema 2.0 bootstrap/effective-member computation finding (review finding 3.1). This issue must not replace or reopen that work.
- Schema 2.1 decisions must precede implementation work in the active Schema 2.0 tracks, especially `S2-R1` runtime descriptor products and `S2-R4` validation.
- Ownership and unqualified-key-scope decisions must remain compatible with the deferred Extension Schema identity design; this issue defines the Core baseline only and does not implement extension-schema identity or migration.
- The `map-holons` repository is the implementation target. This issue is intentionally filed in `map-dev-docs` because the authoritative output is a design revision and implementation-plan reconciliation.

---

## 4. Proposed Solution (Required)

**How would you solve it?**  

Revise the authoritative Schema 2.0 design/specification corpus into an accepted Schema 2.1 semantic revision with independently testable rule IDs and Core-corpus fixtures.

### Issue 1: InheritanceMode Circularity

Make inheritance policy a kernel semantic, represented by a Rust `InheritanceRules` table, rather than descriptor state.

```
    enum InheritanceRule {
        Local,
        Additive,
        Override,
    }

    fn inheritance_rule_for(
        relationship: CoreRelationshipTypeName,
    ) -> InheritanceRule {
        match relationship {
            CoreRelationshipTypeName::InstanceProperties
            | CoreRelationshipTypeName::InstanceRelationships
            | CoreRelationshipTypeName::AffordsCommand
            | CoreRelationshipTypeName::AffordsDance
            | CoreRelationshipTypeName::AffordsOperator
            | CoreRelationshipTypeName::Validations
            | CoreRelationshipTypeName::Constraints
                => InheritanceRule::Additive,

            CoreRelationshipTypeName::InstanceKeyRule
                => InheritanceRule::Override,

            _ => InheritanceRule::Local,
        }
    }
```

`EffectiveValues(T, M)` obtains its policy directly from this table before evaluating any contracts or member definitions. It no longer reads an `InheritanceMode` property from `EffectiveMemberDefinition(M)`.

`Local` replaces the existing `None` behavior: only local values contribute. `Additive` accumulates ancestor and local contributions. `Override` selects the nearest populated contribution set.

#### Consequences

- Remove `InheritanceMode` from the Core Schema, descriptor contracts, completion, TDL syntax/lowering/emission, and descriptor validation.
- Remove all authored `InheritanceMode` fields from the TDL corpus.
- Replace corpus invariants that inspect descriptor values with unit tests for the Rust table.
- Update normative rules so the kernel deliberately selects policy by canonical `CoreRelationshipTypeName`.

#### Validation and constraints

`Validations` is additive: subtype validation rules accumulate with inherited rules.

`Constraints` is also additive: subtypes retain all inherited constraints and may add further constraints that narrow the accepted-value set. A subtype must not relax a supertype constraint. A locally authored weaker constraint is redundant at best and should be rejected as an attempted relaxation.

`InstanceKeyRule` remains override: the nearest populated key-rule selection governs the type.

#### Acceptance criteria

- [ ] Effective-member and effective-contract computation has no dependency on an authored `InheritanceMode` value.
- [ ] Core bootstrap evaluates without a semantic cycle or special completion ordering.
- [ ] `InstanceProperties`, `InstanceRelationships`, affordances, `Validations`, and `Constraints` are additive.
- [ ] `InstanceKeyRule` is override.
- [ ] All other known relationship types are local unless explicitly added to the kernel table.
- [ ] The TDL corpus contains no `InheritanceMode` declarations.
- [ ] Tests cover each non-local rule and confirm the local default.

#### Issue 2
2. Replace the implicit endpoint-axis union with explicit endpoint classification semantics. At minimum distinguish instance-of classification from descriptor-category classification, and specify the meaning of endpoints naming `TypeDescriptor`, `HolonType.TypeDescriptor`, and Instance TypeKind anchors.
3. Define `KeyRuleApplicable(T, K)` (or equivalent) and key derivation failure behavior. It must establish inputs, availability at creation, accepted representations, canonical ordering/encoding, and the chosen policy for abstract keyed descriptors.
4. Define one unambiguous schema-ownership rule for all schema-definition holons, including configured key rules and configured constraints. Apply it to cross-schema reference validation and key scope.
5. Replace topology-derived abstract minimum enforcement with an explicit member-level policy or a stable, expressly authored universal-minimum set.
6. Define `ExecutableValueType` / `CompleteValueDefinition` and require it for a selected ValueType of a concrete property descriptor. Decide whether a complete abstract value definition is admissible.
7. Define the conformance and binding invariant for materialized inverse occurrences, consistent with paired endpoint and directional-cardinality rules.
8. Add Core authoring fixtures/assertions for root anchor/meta-type pairings. Decide whether specialized anchors must have paired meta-types covariant with their parent anchor.
9. Reconcile directly affected documentation and the Core root diagram. Clarify the syntactic-versus-semantic optionality of `Extends`, direct descendants of `RelationshipType`, member-name rename evolution, terminology, and referenced affordance ownership.
Do not introduce a kernel table of fixed descriptor categories merely to solve these decisions. Preserve graph-defined pairing and the separate `DescribedBy` / `Extends` axes.

---

### 5. Scope and Impact (Required)

**What does this impact?**  

- Authoritative documentation: `schema-design-spec.md`, `descriptor-semantics-rules.md`, `schema-2.0.md`, `map-type-system.md`, the relationship and value-constraint specifications, TDL specification, and the Core root diagram where affected.
- Core Schema corpus: new or adjusted fixtures covering accepted and rejected endpoint modes, configured rule ownership, key-rule input completeness, abstract minimum policy, value-type executability, inverse binding, and anchor pairing.
- `map-holons` implementation follow-up: `HolonDescriptor` effective semantic products, Holon Validator errors/checks, TDL lowering/index validation, schema ownership/indexing, key-rule execution, and validation fixtures.

Out of scope:

- the bootstrap/effective-member computation resolution already underway;
- subtype member refinement/variance;
- a general empty-override/tombstone feature unless separately selected after the monotonicity decision;
- broad Extension Schema identity, qualified-key namespaces, version migration, aliases, or deletion-policy execution semantics;
- changing persisted keys or defaults retroactively.

---

### 6. Testing Considerations (Required)

**How will this enhancement be tested?**

- Add normative Core-corpus fixtures and rule-index coverage for each new or revised `DS-*` invariant.
- Add positive/negative endpoint cases that separately prove instance classification, descriptor-category classification, and any deliberately supported union mode.
- Add configured `FormatRule` cases for missing, optional-without-default, invalid-representation, and unordered parameters; prove the accepted key-rule inputs derive the expected canonical key.
- Add within-schema and cross-schema configured rule/constraint ownership cases; prove dependency validation and key scope are total.
- Add abstract descriptor fixtures proving the explicit minimum policy is stable when contract declarations move in the meta-type hierarchy.
- Add selected ValueType cases for incomplete abstract, complete abstract (if permitted), and concrete executable definitions.
- Add declared/inverse occurrence cases that prove both directions bind and validate through the adopted rule.
- In `map-holons`, extend unit/integration coverage around `map_schema_semantic`, `tools/map-schema`, descriptor wrappers, and validated Core-schema loading once the design is accepted.

---

### 7. Definition of Done (Required)

**When is this enhancement complete?**

- [ ] Schema 2.1 records accepted decisions for all six semantic gaps above, without reopening finding 3.1.
- [ ] Each decision has normative predicates, preconditions, failure behavior, and stable `DS-*` rule IDs where validation is required.
- [ ] The Core Schema corpus has fixtures/assertions for root anchor pairings and every revised semantic boundary.
- [ ] The authoritative documents, TDL specification, and Core root diagram agree on contract topology and terminology.
- [ ] The implementation plan maps each new/revised rule to the correct Schema 2.0 migration track or explicitly marks it as deferred follow-up.
- [ ] `map-holons` implementation impact and current gaps are documented without silently treating legacy `DescriptorKind` checks or TDL lowering behavior as the Schema 2.1 semantic authority.
- [ ] Deferred Extension Schema identity/evolution work remains explicitly out of scope and no new incompatible key namespace is implied.

<details>
<summary>Optional Details (Expand if needed)</summary>

### 8. Alternatives Considered

**What other solutions did you think about?**

- Keep the current endpoint union and require unrelated source-contract constraints for descriptor-only use cases. Rejected: it cannot express the intended predicate locally and makes correctness accidental.
- Hard-code descriptor-category pairing in the kernel. Rejected: it breaks the graph-defined extension model. Core fixtures plus an explicit covariance policy preserve extensibility.
- Treat every generic instance in a schema file as a descriptor component. Rejected: ownership should cover schema-definition holons without conflating arbitrary runtime data with schema content.
- Require every selected value type to be concrete. This is simpler, but the design may intentionally permit an abstract value type whose effective definition is complete; decide through `ExecutableValueType` instead.

---

### 9. Risks or Concerns

**What could go wrong?**

- This is a semantic revision, not a documentation sweep. Decisions change validator behavior and could invalidate parts of the current Core corpus or migration assumptions.
- Over-scoping into generic schema evolution, extension identity, or deletion execution would delay the bounded kernel revision.
- A too-general endpoint mode system can make relationship authoring opaque; surface only the minimum modes that represent the two existing classification axes.
- The current implementation contains transitional role/kind checks and descriptor wrappers. It must be measured against accepted predicates rather than used to redefine them.

---

### 10. Additional Context

**Any supporting material?**

Authoritative DevDocs sources:

- `docs/core/type-system/schema-design-spec.md`
- `docs/core/type-system/descriptor-semantics-rules.md`
- `docs/core/type-system/schema-2.0.md`
- `docs/core/type-system/relationship-constraints-design-spec.md`
- `docs/core/type-system/value-constraints-design-spec.md`
- `docs/core/type-system/tdl/tdl-spec.md`
- `docs/core/type-system/tdl/tdl-impl-plan-v2.md`
- `docs/core/type-system/tdl/tdl-workplan-reconciliation.md`

Implementation reconnaissance (`map-holons`, read-only):

- `shared_crates/map_schema_semantic/src/schema_index.rs` currently validates reference roles against `DescriptorKind` categories.
- `tools/map-schema/src/tdl_compiler.rs` adds `ComponentOf` only for non-generic descriptor declarations; generic instances intentionally do not receive it.
- `shared_crates/holons_core/src/descriptors/key_rule_descriptor.rs` classifies key rules through the `Extends` chain, but does not establish rule-input applicability.
- `shared_crates/holons_core/src/descriptors/value_descriptor.rs` dispatches runtime value validation through a resolved value kind; Schema 2.1 must define the admissibility predicate it consumes.

</details>
